"""Diff the resolved TwoLeg velocity env config against microduck_rl's.

Both dumps come from ``dump_env_cfg.py``, which imports the real config object
under each project's own venv. This script only compares JSON, so it runs on
stock python with no mjlab dependency.

    ./.venv/bin/python twoleg_rl/dump_env_cfg.py twoleg  .audit/cfg_twoleg.json
    (cd ../microduck_rl && ./.venv/bin/python \\
        /home/kenpeter/work/twoleg/training/twoleg_rl/dump_env_cfg.py microduck \\
        ../twoleg/.audit/cfg_microduck.json)
    python3 twoleg_rl/diff_vs_microduck.py .audit/cfg_twoleg.json \\
        .audit/cfg_microduck.json > .audit/twoleg-vs-microduck.md

Lists compare as whole leaves; dicts recurse, so per-regex and per-param
differences show up as separate rows.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

MJLAB_PREFIX = "mjlab."
LEFT_LABEL = "TwoLeg"
RIGHT_LABEL = "microduck_rl"


def flatten(node: Any, prefix: str = "") -> dict[str, Any]:
    """Flatten nested dicts into dotted paths. Lists and scalars are leaves."""
    out: dict[str, Any] = {}
    if isinstance(node, dict):
        for k, v in node.items():
            out.update(flatten(v, f"{prefix}.{k}" if prefix else str(k)))
    else:
        out[prefix] = node
    return out


def func_origin(value: Any) -> str:
    """Classify a serialized callable by which package provides it.

    Accepts both the ``{"__func__": dotted}`` form and a bare dotted string,
    because flatten() already unwraps the dict to its string leaf.
    """
    if isinstance(value, dict) and "__func__" in value:
        name = value["__func__"]
    elif isinstance(value, str) and value.count(".") >= 1 and " " not in value:
        name = value
    else:
        return ""
    if name.startswith(MJLAB_PREFIX):
        return "mjlab"
    if "microduck" in name:
        return "microduck_rl"
    if "twoleg" in name:
        return "twoleg"
    return "other"


def show(value: Any, width: int = 90) -> str:
    if isinstance(value, (dict, list)):
        text = json.dumps(value, sort_keys=True)
    elif isinstance(value, bool) or value is None:
        text = repr(value)
    elif isinstance(value, str):
        text = value
    elif isinstance(value, float):
        text = f"{value:g}"
    else:
        text = str(value)
    text = " ".join(text.split())
    return text if len(text) <= width else text[: width - 3] + "..."


def cell(md: Any, jl: Any) -> str:
    """Render one side of a row, marking project-local callables."""
    origin = func_origin(md) or func_origin(jl)
    text = show(md if md is not None else jl)
    if origin in ("microduck_rl", "twoleg", "other"):
        text = f"[{origin}] {text}"
    return text.replace("|", "\\|")


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    left = json.loads(Path(sys.argv[1]).read_text())
    right = json.loads(Path(sys.argv[2]).read_text())

    lf = flatten(left)
    rf = flatten(right)
    keys = sorted(set(lf) | set(rf))

    rows: list[tuple[str, str, str, str]] = []  # status, path, left, right
    for key in keys:
        if key.startswith("_"):
            continue
        a, b = lf.get(key, "<absent>"), rf.get(key, "<absent>")
        if a == b:
            continue
        if a == "<absent>":
            status = "duck-only"
        elif b == "<absent>":
            status = "twoleg-only"
        elif func_origin(a) or func_origin(b):
            # Both present, both callables: same basename means a reimplementation.
            na = a.get("__func__", "").split(".")[-1] if isinstance(a, dict) else None
            nb = b.get("__func__", "").split(".")[-1] if isinstance(b, dict) else None
            status = "same-name-own-copy" if na == nb else "different-func"
        else:
            status = "value-differs"
        rows.append((status, key, a, b))

    same = [k for k in keys if not k.startswith("_") and k in lf and k in rf and lf[k] == rf[k]]

    out: list[str] = []
    out.append(f"# {LEFT_LABEL} vs {RIGHT_LABEL}: resolved velocity-env config diff\n")
    out.append(
        "Generated by `training/twoleg_rl/diff_vs_microduck.py` from "
        "`dump_env_cfg.py` output. Values are read off the live config objects, "
        "so mjlab base defaults inherited by both projects are included.\n"
    )
    out.append(f"- identical leaf values: **{len(same)}**")
    out.append(f"- differing leaf values: **{len(rows)}**\n")

    out.append("## Robot (from the compiled MuJoCo spec)\n")
    out.append("| field | " + LEFT_LABEL + " | " + RIGHT_LABEL + " |")
    out.append("| --- | --- | --- |")
    lr, rr = flatten(left["_robot"]), flatten(right["_robot"])
    for key in sorted(set(lr) | set(rr)):
        if key.endswith("actuator_names") or key.endswith("declared_joint_names"):
            continue
        out.append(f"| `{key}` | {show(lr.get(key, '<absent>'))} | {show(rr.get(key, '<absent>'))} |")
    out.append("")

    order = ["same-name-own-copy", "different-func", "value-differs", "duck-only", "twoleg-only"]
    titles = {
        "same-name-own-copy": "Same function name, project-local copy (reimplementation)",
        "different-func": "Different function behind the same knob",
        "value-differs": "Same knob, different value",
        "duck-only": "microduck_rl only",
        "twoleg-only": "TwoLeg only",
    }
    for status in order:
        subset = [r for r in rows if r[0] == status]
        if not subset:
            continue
        out.append(f"## {titles[status]} ({len(subset)})\n")
        out.append("| knob | " + LEFT_LABEL + " | " + RIGHT_LABEL + " |")
        out.append("| --- | --- | --- |")
        for _, key, a, b in subset:
            out.append(f"| `{key}` | {cell(a, b)} | {cell(b, a)} |")
        out.append("")

    out.append("## Identical (abridged)\n")
    out.append("<details><summary>" + str(len(same)) + " identical leaf values</summary>\n")
    for key in same:
        out.append(f"- `{key}` = {show(lf[key], 70)}")
    out.append("\n</details>\n")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())